### ISSUE TITLE
with-rss2 & rss-channel-header's parameters need updating as xml-emitter updated to 1.0.5

### ISSUE THREAD

**Issue by VaughnLi** [VitoVan/vito.sdf.org#1]
hi, Vito:
as xml-emitter updated to version 1.0.5, rss2 & rss-channel-header functions in server.lisp need to update their parameters now.

Thanks for your awesome blog theme btw.
Happy New Year ~

**Comment by VitoVan** [comment]
Seems like a BUG in xml-emitter:

```lisp
CL-USER> (ql:quickload 'xml-emitter)
To load "xml-emitter":
  Load 1 ASDF system:
    xml-emitter
; Loading "xml-emitter"

(XML-EMITTER)
CL-USER> (use-package 'xml-emitter)
T
CL-USER> (with-output-to-string (s) (with-rss2 (s)))
; in: WITH-OUTPUT-TO-STRING (S)
;     (WITH-RSS2 (S))
; --> WITH-XML-OUTPUT LET WITH-TAG LET PROGN XML-EMITTER::START-TAG 
; ==>
;   (("version" "2.0"))
; 
; caught ERROR:
;   illegal function call
; 
; compilation unit finished
;   caught 1 ERROR condition
; Evaluation aborted on #<SB-INT:COMPILED-PROGRAM-ERROR {100926A0D3}>.
```

**Comment by VitoVan** [comment]
https://github.com/VitoVan/xml-emitter/issues/6

**Comment by VitoVan** [comment]
Thank you @VaughnLi , happy new year to you too.

**Comment by VitoVan** [comment]
I have committed a temporally fix:

```lisp
(ql-dist:install-dist "http://beta.quicklisp.org/dist/quicklisp/2019-10-08/distinfo.txt" :replace t)
```

it's ugly, but for now it works.

**Comment by VaughnLi** [comment]
Thanks. 
I know few about lisp, but if add :attrs in with-rss2 and :generator in rss-channel-header, it works too. 😺 
`with-rss2 (s :encoding "UTF-8" :attrs '(("version" "2.0")))
    (rss-channel-header "xxx" "http://xxxurl"
                          :description "xxx"
                          :generator "xml-emitter"
                          :image "http://xxxurl.png"
                          :image-title "xxx's avatar")`

**Comment by VitoVan** [comment]
`rss-channel-header` is fine, since it's just a normal function, no magic macro expanding effects involved, you can still use it without `:generator`.

`with-rss2` is not OK, because it's a macro, and expand it's default arg `'(("version" "2.0"))` to `(("version" "2.0"))`, then `"version"` is treated as a function, when calling `"version"` as a function which obvious it is a string, shit happened.

Your solution works because your provided argument to `:attrs` won't be expanded as the original one, and the `'` is reserved after the macro expand operation.

Check this:

```lisp
XML-EMITTER> (macroexpand '(with-rss2 (s)))
(LET ((*XML-OUTPUT-STREAM* S))
  (FORMAT *XML-OUTPUT-STREAM*
          "<?xml version=\"1.0\" encoding=~S~:[~; standalone=\"~:[no~;yes~]\"~]?>~%"
          "ISO-8859-1" NIL NIL)
  (WITH-TAG ("rss" (("version" "2.0"))) ;; <------ HERE
    (WITH-TAG ("channel"))))
T
XML-EMITTER> (macroexpand '(with-rss2 (s :attrs '(("version" "2.0")))))
(LET ((*XML-OUTPUT-STREAM* S))
  (FORMAT *XML-OUTPUT-STREAM*
          "<?xml version=\"1.0\" encoding=~S~:[~; standalone=\"~:[no~;yes~]\"~]?>~%"
          "ISO-8859-1" NIL NIL)
  (WITH-TAG ("rss" '(("version" "2.0"))) ;; <------ HERE
    (WITH-TAG ("channel"))))
T
``` 

It's not easy to handle macros easily, so I always try to avoid macro.

**Comment by VitoVan** [comment]
And, I'll keep this issue open until the upstream (xml-emitter) fix that.

**Comment by VitoVan** [comment]
This issue have been fixed by the xml-emitter upstream:

https://github.com/VitoVan/xml-emitter/pull/9

And published by Quicklisp with newer version:

http://blog.quicklisp.org/2020/02/february-2020-quicklisp-dist-update-now.html

The temporary fix have been reverted on this repository:

https://github.com/VitoVan/vitovan.github.io/commit/d8831e8cd4fb8560612afa3d5373a092ed4936c0

Now after we do `(ql:update-dist "quicklisp")`, things will go back normal.

So, I'm gonna close this issue, thank you very much for pay attention on this VaughnLi, wish you happy and say hello to Ygritte too.
